version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarm:
      - 6
      - 7
archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
changelog:
  sort: asc
