name: docker
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: raviqqe/muffet
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
