name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang
    steps:
      - uses: actions/checkout@v2
      - run: tools/build.sh
      - run: tools/lint.sh
      - run: tools/test.sh
      - uses: codecov/codecov-action@v1
